-- MERGE idempotente de AUX.STG_NEW_EVENTS contra ANALYTICS.PROC_FACT_EVENT.
MERGE INTO MEETUP_DB.ANALYTICS.PROC_FACT_EVENT t
USING MEETUP_DB.AUX.STG_NEW_EVENTS s
  ON t.EVENT_ID = s.EVENT_ID
WHEN MATCHED THEN UPDATE SET
  t.YES_RSVP_COUNT = s.YES_RSVP_COUNT,
  t.EVENT_STATUS   = s.EVENT_STATUS,
  t.UPDATED_AT     = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
  (EVENT_ID, GROUP_ID, EVENT_NAME, EVENT_STATUS, YES_RSVP_COUNT,
   IS_SIMULATED, CREATED_AT, UPDATED_AT)
VALUES
  (s.EVENT_ID, s.GROUP_ID, s.EVENT_NAME, s.EVENT_STATUS, s.YES_RSVP_COUNT,
   s.IS_SIMULATED, s.CREATED_AT, CURRENT_TIMESTAMP());
