-- Metricas agregadas por grupo.
CREATE OR REPLACE TABLE MEETUP_DB.ANALYTICS.PROC_GROUP_METRICS AS
SELECT f.GROUP_ID, d.GROUP_NAME, d.CATEGORY_NAME, d.CITY, d.COUNTRY,
       COUNT(*)                AS TOTAL_EVENTS,
       SUM(f.YES_RSVP_COUNT)   AS TOTAL_RSVP,
       AVG(f.YES_RSVP_COUNT)   AS AVG_RSVP,
       MAX(f.CREATED_AT)       AS LAST_EVENT_AT
FROM MEETUP_DB.ANALYTICS.PROC_FACT_EVENT f
JOIN MEETUP_DB.AUX.DIM_GROUP d ON f.GROUP_ID = d.GROUP_ID
GROUP BY f.GROUP_ID, d.GROUP_NAME, d.CATEGORY_NAME, d.CITY, d.COUNTRY;
