-- Metricas agregadas por ciudad.
CREATE OR REPLACE TABLE MEETUP_DB.ANALYTICS.PROC_CITY_METRICS AS
SELECT c.CITY_ID, c.CITY, c.COUNTRY,
       COUNT(*)                   AS TOTAL_EVENTS,
       SUM(f.YES_RSVP_COUNT)      AS TOTAL_RSVP,
       COUNT(DISTINCT f.GROUP_ID) AS TOTAL_GROUPS
FROM MEETUP_DB.ANALYTICS.PROC_FACT_EVENT f
JOIN MEETUP_DB.AUX.DIM_GROUP g ON f.GROUP_ID = g.GROUP_ID
JOIN MEETUP_DB.AUX.DIM_CITY  c ON g.CITY_ID  = c.CITY_ID
GROUP BY c.CITY_ID, c.CITY, c.COUNTRY;
