-- Registro de la corrida en OPS.PIPELINE_RUN_LOG.
INSERT INTO MEETUP_DB.OPS.PIPELINE_RUN_LOG
SELECT CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
       '{{ run_id }}',
       (SELECT COUNT(*) FROM MEETUP_DB.ANALYTICS.PROC_FACT_EVENT),
       (SELECT COUNT(*) FROM MEETUP_DB.AUX.STG_NEW_EVENTS);
