-- 08_dim_member_group.sql
-- AUX.DIM_MEMBER_GROUP: membresias tipadas SIN columnas personales.

CREATE OR REPLACE TABLE MEETUP_DB.AUX.DIM_MEMBER_GROUP AS
WITH base AS (
  SELECT
    TRY_TO_NUMBER(NULLIF(TRIM(MEMBER_ID), ''))    AS MEMBER_ID,
    TRY_TO_NUMBER(NULLIF(TRIM(GROUP_ID), ''))     AS GROUP_ID,
    NULLIF(TRIM(CITY), '')                        AS CITY,
    NULLIF(TRIM(STATE), '')                       AS STATE,
    NULLIF(TRIM(COUNTRY), '')                     AS COUNTRY,
    NULLIF(TRIM(MEMBER_STATUS), '')               AS MEMBER_STATUS,
    TRY_TO_NUMBER(NULLIF(TRIM(JOINED), ''))       AS JOINED_EPOCH,
    TRY_TO_NUMBER(NULLIF(TRIM(VISITED), ''))      AS VISITED_EPOCH
  FROM MEETUP_DB.RAW.MEMBERS
)
SELECT
  MEMBER_ID,
  GROUP_ID,
  CITY,
  STATE,
  COUNTRY,
  MEMBER_STATUS,
  CASE
    WHEN JOINED_EPOCH > 100000000000 THEN TO_TIMESTAMP_NTZ(JOINED_EPOCH / 1000)
    WHEN JOINED_EPOCH IS NOT NULL    THEN TO_TIMESTAMP_NTZ(JOINED_EPOCH)
  END                                           AS JOINED_AT,
  CASE
    WHEN VISITED_EPOCH > 100000000000 THEN TO_TIMESTAMP_NTZ(VISITED_EPOCH / 1000)
    WHEN VISITED_EPOCH IS NOT NULL    THEN TO_TIMESTAMP_NTZ(VISITED_EPOCH)
  END                                           AS VISITED_AT
FROM base;
