-- 09_member_dq_check.sql
-- Chequeo de calidad de AUX.DIM_MEMBER_GROUP para SQLCheckOperator.

SELECT
    COUNT_IF(MEMBER_ID IS NULL OR GROUP_ID IS NULL) = 0
    AND COUNT(*) = COUNT(DISTINCT MEMBER_ID || '-' || GROUP_ID)
    AND COUNT_IF(d.GROUP_ID IS NULL) / COUNT(*) < 0.01   AS PASS
FROM MEETUP_DB.AUX.DIM_MEMBER_GROUP m
LEFT JOIN MEETUP_DB.AUX.DIM_GROUP d
       ON m.GROUP_ID = TRY_TO_NUMBER(NULLIF(TRIM(TO_VARCHAR(d.GROUP_ID)), ''));
