-- 10_member_metrics.sql
-- Metricas agregadas de miembros, conciliacion con GROUPS.MEMBERS y estado de la ultima construccion.

CREATE OR REPLACE TABLE MEETUP_DB.ANALYTICS.PROC_MEMBER_RECONCILIATION AS
WITH dim AS (
  SELECT TRY_TO_NUMBER(NULLIF(TRIM(TO_VARCHAR(GROUP_ID)), '')) AS GROUP_ID,
         GROUP_NAME, CATEGORY_NAME
  FROM MEETUP_DB.AUX.DIM_GROUP
  QUALIFY ROW_NUMBER() OVER (PARTITION BY GROUP_ID ORDER BY GROUP_NAME) = 1
),
actual AS (
  SELECT GROUP_ID, COUNT(DISTINCT MEMBER_ID) AS ACTUAL_MEMBERS
  FROM MEETUP_DB.AUX.DIM_MEMBER_GROUP
  WHERE GROUP_ID IS NOT NULL AND MEMBER_ID IS NOT NULL
  GROUP BY GROUP_ID
),
declared AS (
  SELECT TRY_TO_NUMBER(NULLIF(TRIM(TO_VARCHAR(GROUP_ID)), '')) AS GROUP_ID,
         TRY_TO_NUMBER(NULLIF(TRIM(TO_VARCHAR(MEMBERS)), ''))  AS DECLARED_MEMBERS
  FROM MEETUP_DB.RAW.GROUPS
  QUALIFY ROW_NUMBER() OVER (PARTITION BY GROUP_ID ORDER BY MEMBERS DESC) = 1
)
SELECT
    a.GROUP_ID,
    d.GROUP_NAME,
    COALESCE(d.CATEGORY_NAME, '(sin categoria)')          AS CATEGORY_NAME,
    g.DECLARED_MEMBERS,
    a.ACTUAL_MEMBERS,
    a.ACTUAL_MEMBERS - g.DECLARED_MEMBERS                 AS DIFF,
    IFF(g.DECLARED_MEMBERS > 0,
        ABS(a.ACTUAL_MEMBERS - g.DECLARED_MEMBERS) * 100.0 / g.DECLARED_MEMBERS,
        NULL)                                             AS ABS_PCT_DIFF
FROM actual a
JOIN declared g ON a.GROUP_ID = g.GROUP_ID
LEFT JOIN dim d ON a.GROUP_ID = d.GROUP_ID
WHERE a.ACTUAL_MEMBERS >= 5;

CREATE OR REPLACE TABLE MEETUP_DB.ANALYTICS.PROC_MEMBER_METRICS AS
WITH dim AS (
  SELECT TRY_TO_NUMBER(NULLIF(TRIM(TO_VARCHAR(GROUP_ID)), '')) AS GROUP_ID,
         GROUP_NAME, CATEGORY_NAME
  FROM MEETUP_DB.AUX.DIM_GROUP
  QUALIFY ROW_NUMBER() OVER (PARTITION BY GROUP_ID ORDER BY GROUP_NAME) = 1
),
mg AS (
  SELECT m.MEMBER_ID, m.GROUP_ID, m.JOINED_AT,
         COALESCE(d.CATEGORY_NAME, '(sin categoria)') AS CATEGORY_NAME,
         COALESCE(d.GROUP_NAME, '(sin nombre)')       AS GROUP_NAME,
         COALESCE(m.CITY, '(sin ciudad)')             AS CITY
  FROM MEETUP_DB.AUX.DIM_MEMBER_GROUP m
  LEFT JOIN dim d ON m.GROUP_ID = d.GROUP_ID
  WHERE m.MEMBER_ID IS NOT NULL AND m.GROUP_ID IS NOT NULL
),

per_member AS (
  SELECT MEMBER_ID, COUNT(DISTINCT GROUP_ID) AS N_GROUPS
  FROM mg GROUP BY MEMBER_ID
),
dist AS (
  SELECT 'DIST_MEMBERSHIPS' AS T, 'en_1_grupo'        AS K, COUNT(*)::NUMBER(38,4) AS V
         FROM per_member WHERE N_GROUPS = 1
  UNION ALL SELECT 'DIST_MEMBERSHIPS', 'en_2_a_3_grupos', COUNT(*) FROM per_member WHERE N_GROUPS BETWEEN 2 AND 3
  UNION ALL SELECT 'DIST_MEMBERSHIPS', 'en_4_o_mas_grupos', COUNT(*) FROM per_member WHERE N_GROUPS >= 4
),

per_group AS (
  SELECT GROUP_NAME, CATEGORY_NAME, COUNT(DISTINCT MEMBER_ID) AS N
  FROM mg GROUP BY GROUP_NAME, CATEGORY_NAME
),
by_group AS (
  SELECT 'MEMBERS_BY_GROUP' AS T,
         IFF(SUM(N) >= 5, GROUP_NAME, 'otros (<5 miembros)') AS K,
         SUM(N)::NUMBER(38,4) AS V
  FROM per_group GROUP BY 1
),
per_cat AS (
  SELECT CATEGORY_NAME, COUNT(DISTINCT MEMBER_ID) AS N FROM mg GROUP BY CATEGORY_NAME
),
by_cat AS (
  SELECT 'MEMBERS_BY_CATEGORY' AS T,
         IFF(N >= 5, CATEGORY_NAME, 'otros (<5 miembros)') AS K,
         N::NUMBER(38,4) AS V
  FROM per_cat
),
by_city AS (
  SELECT 'MEMBERS_BY_CITY' AS T,
         IFF(N >= 5, CITY, 'otros (<5 miembros)') AS K,
         N::NUMBER(38,4) AS V
  FROM (
    SELECT CITY, COUNT(DISTINCT MEMBER_ID) AS N FROM mg GROUP BY CITY
  )
),

top3 AS (
  SELECT CATEGORY_NAME AS CAT FROM per_cat ORDER BY N DESC LIMIT 3
),
member_cat AS (
  SELECT DISTINCT MEMBER_ID, CATEGORY_NAME AS CAT FROM mg
),
overlap AS (
  SELECT 'OVERLAP_TOP_CATEGORIES' AS T,
         a.CAT || ' + ' || b.CAT  AS K,
         COUNT(DISTINCT a.MEMBER_ID)::NUMBER(38,4) AS V
  FROM member_cat a
  JOIN member_cat b ON a.MEMBER_ID = b.MEMBER_ID AND a.CAT < b.CAT
  WHERE a.CAT IN (SELECT CAT FROM top3) AND b.CAT IN (SELECT CAT FROM top3)
  GROUP BY 1, 2
),

ts AS (
  SELECT 'ALTAS_POR_MES' AS T,
         TO_VARCHAR(JOINED_AT, 'YYYY-MM') AS K,
         COUNT(DISTINCT MEMBER_ID)::NUMBER(38,4) AS V
  FROM mg WHERE JOINED_AT IS NOT NULL
  GROUP BY 1, 2
),

mt AS (
  SELECT TRY_TO_NUMBER(NULLIF(TRIM(TO_VARCHAR(MEMBER_ID)), '')) AS MEMBER_ID,
         TRY_TO_NUMBER(NULLIF(TRIM(TO_VARCHAR(TOPIC_ID)), ''))  AS TOPIC_ID
  FROM MEETUP_DB.RAW.MEMBERS_TOPICS
),
topics AS (
  SELECT TRY_TO_NUMBER(NULLIF(TRIM(TO_VARCHAR(TOPIC_ID)), '')) AS TOPIC_ID,
         COALESCE(TOPIC_NAME, '(sin nombre)')                  AS TOPIC_NAME
  FROM MEETUP_DB.RAW.TOPICS
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TOPIC_ID ORDER BY TOPIC_NAME) = 1
),
cat_topic AS (
  SELECT mc.CAT, t.TOPIC_NAME, COUNT(DISTINCT mc.MEMBER_ID) AS N
  FROM member_cat mc
  JOIN mt ON mc.MEMBER_ID = mt.MEMBER_ID
  JOIN topics t ON mt.TOPIC_ID = t.TOPIC_ID
  WHERE mc.CAT IN (SELECT CAT FROM top3)
  GROUP BY 1, 2
  QUALIFY ROW_NUMBER() OVER (PARTITION BY mc.CAT ORDER BY N DESC, t.TOPIC_NAME) <= 5
),
by_topic AS (
  SELECT 'TOPIC_BY_CATEGORY' AS T, CAT || ' :: ' || TOPIC_NAME AS K, N::NUMBER(38,4) AS V
  FROM cat_topic
),

recon AS (
  SELECT
    'RECON' AS T, 'GRUPOS_CONCILIADOS'        AS K, COUNT(*)::NUMBER(38,4)                 AS V FROM ANALYTICS.PROC_MEMBER_RECONCILIATION
  UNION ALL SELECT 'RECON', 'PCT_DENTRO_25PCT',
          COUNT_IF(ABS_PCT_DIFF <= 25) * 100.0 / COUNT(*)                              FROM ANALYTICS.PROC_MEMBER_RECONCILIATION
  UNION ALL SELECT 'RECON', 'MEDIANA_ABS_PCT_DIFF',
          COALESCE(MEDIAN(ABS_PCT_DIFF), 0)                                            FROM ANALYTICS.PROC_MEMBER_RECONCILIATION
  UNION ALL SELECT 'RECON', 'SUMA_DECLARADA',   COALESCE(SUM(DECLARED_MEMBERS), 0)     FROM ANALYTICS.PROC_MEMBER_RECONCILIATION
  UNION ALL SELECT 'RECON', 'SUMA_REAL',        COALESCE(SUM(ACTUAL_MEMBERS), 0)       FROM ANALYTICS.PROC_MEMBER_RECONCILIATION
),

tot AS (
  SELECT COUNT(DISTINCT MEMBER_ID)   AS TOTAL_MEMBERS,
         COUNT(*)                    AS TOTAL_MEMBERSHIPS,
         COUNT(DISTINCT GROUP_ID)    AS GROUPS_WITH_MEMBERS,
         COUNT(*) / NULLIF(COUNT(DISTINCT MEMBER_ID), 0) AS AVG_MEMBERSHIPS_PER_MEMBER
  FROM mg
),
totals AS (
  SELECT 'TOTALS' AS T, 'MIEMBROS_UNICOS'     AS K, TOTAL_MEMBERS::NUMBER(38,4)             AS V FROM tot
  UNION ALL SELECT 'TOTALS', 'MEMBRESIAS',          TOTAL_MEMBERSHIPS::NUMBER(38,4)        FROM tot
  UNION ALL SELECT 'TOTALS', 'GRUPOS_CON_MIEMBROS', GROUPS_WITH_MEMBERS::NUMBER(38,4)      FROM tot
  UNION ALL SELECT 'TOTALS', 'MEDIA_MEMBRESIAS_POR_MIEMBRO',
          COALESCE(AVG_MEMBERSHIPS_PER_MEMBER, 0)                                      FROM tot
)

SELECT T, K, V FROM dist
UNION ALL SELECT T, K, V FROM by_group
UNION ALL SELECT T, K, V FROM by_cat
UNION ALL SELECT T, K, V FROM by_city
UNION ALL SELECT T, K, V FROM overlap
UNION ALL SELECT T, K, V FROM ts
UNION ALL SELECT T, K, V FROM recon
UNION ALL SELECT T, K, V FROM totals;

CREATE TABLE IF NOT EXISTS MEETUP_DB.OPS.MEMBER_METRICS_STATE (
  LAST_ROW_COUNT   NUMBER,
  LAST_UPDATED_AT  TIMESTAMP_NTZ
);
DELETE FROM MEETUP_DB.OPS.MEMBER_METRICS_STATE;
INSERT INTO MEETUP_DB.OPS.MEMBER_METRICS_STATE
SELECT COUNT(*), CURRENT_TIMESTAMP()::TIMESTAMP_NTZ FROM MEETUP_DB.RAW.MEMBERS;
