-- File format y stage interno para la ingesta de members.
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MEETUP;

CREATE FILE FORMAT IF NOT EXISTS MEETUP_DB.RAW.FF_CSV_MEMBERS
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL')
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
  ENCODING = 'UTF8';

CREATE STAGE IF NOT EXISTS MEETUP_DB.RAW.STG_MEMBERS
  FILE_FORMAT = MEETUP_DB.RAW.FF_CSV_MEMBERS;

GRANT USAGE ON SCHEMA MEETUP_DB.RAW TO ROLE ROLE_AIRFLOW;
GRANT CREATE TABLE ON SCHEMA MEETUP_DB.RAW TO ROLE ROLE_AIRFLOW;
GRANT USAGE ON FILE FORMAT MEETUP_DB.RAW.FF_CSV_MEMBERS TO ROLE ROLE_AIRFLOW;
GRANT READ, WRITE ON STAGE MEETUP_DB.RAW.STG_MEMBERS TO ROLE ROLE_AIRFLOW;

SHOW STAGES LIKE 'STG_MEMBERS' IN SCHEMA MEETUP_DB.RAW;
SHOW GRANTS TO ROLE ROLE_AIRFLOW;
