-- 08_grants_role_airflow.sql
-- Permisos consolidados de ROLE_AIRFLOW sobre todos los objetos que usan los DAGs.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MEETUP;

GRANT USAGE ON DATABASE MEETUP_DB TO ROLE ROLE_AIRFLOW;
GRANT USAGE ON SCHEMA MEETUP_DB.RAW       TO ROLE ROLE_AIRFLOW;
GRANT USAGE ON SCHEMA MEETUP_DB.AUX       TO ROLE ROLE_AIRFLOW;
GRANT USAGE ON SCHEMA MEETUP_DB.ANALYTICS TO ROLE ROLE_AIRFLOW;
GRANT USAGE ON SCHEMA MEETUP_DB.OPS       TO ROLE ROLE_AIRFLOW;

GRANT SELECT ON ALL TABLES    IN SCHEMA MEETUP_DB.RAW TO ROLE ROLE_AIRFLOW;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MEETUP_DB.RAW TO ROLE ROLE_AIRFLOW;

GRANT CREATE TABLE ON SCHEMA MEETUP_DB.AUX TO ROLE ROLE_AIRFLOW;
GRANT SELECT ON ALL TABLES    IN SCHEMA MEETUP_DB.AUX TO ROLE ROLE_AIRFLOW;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MEETUP_DB.AUX TO ROLE ROLE_AIRFLOW;

GRANT CREATE TABLE ON SCHEMA MEETUP_DB.ANALYTICS TO ROLE ROLE_AIRFLOW;
GRANT CREATE TABLE ON SCHEMA MEETUP_DB.OPS       TO ROLE ROLE_AIRFLOW;
GRANT SELECT ON ALL TABLES    IN SCHEMA MEETUP_DB.ANALYTICS TO ROLE ROLE_AIRFLOW;
GRANT SELECT ON ALL TABLES    IN SCHEMA MEETUP_DB.OPS       TO ROLE ROLE_AIRFLOW;

GRANT USAGE, READ, WRITE ON STAGE MEETUP_DB.AUX.S3_EXPORT_STAGE TO ROLE ROLE_AIRFLOW;

SHOW GRANTS TO ROLE ROLE_AIRFLOW;
