-- 09_member_analytics.sql
-- Cascarones vacios de las tablas de miembros + verificaciones previas.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MEETUP;

CREATE TABLE IF NOT EXISTS MEETUP_DB.AUX.DIM_MEMBER_GROUP (
  MEMBER_ID      NUMBER,
  GROUP_ID       NUMBER,
  CITY           VARCHAR,
  STATE          VARCHAR,
  COUNTRY        VARCHAR,
  MEMBER_STATUS  VARCHAR,
  JOINED_AT      TIMESTAMP_NTZ,
  VISITED_AT     TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS MEETUP_DB.ANALYTICS.PROC_MEMBER_METRICS (
  METRIC_TYPE  VARCHAR(40),
  METRIC_KEY   VARCHAR(200),
  METRIC_VALUE NUMBER(38,4)
);

CREATE TABLE IF NOT EXISTS MEETUP_DB.ANALYTICS.PROC_MEMBER_RECONCILIATION (
  GROUP_ID          NUMBER,
  GROUP_NAME        VARCHAR,
  CATEGORY_NAME     VARCHAR,
  DECLARED_MEMBERS  NUMBER,
  ACTUAL_MEMBERS    NUMBER,
  DIFF              NUMBER,
  ABS_PCT_DIFF      NUMBER(38,4)
);

CREATE TABLE IF NOT EXISTS MEETUP_DB.OPS.MEMBER_METRICS_STATE (
  LAST_ROW_COUNT   NUMBER,
  LAST_UPDATED_AT  TIMESTAMP_NTZ
);

GRANT SELECT ON MEETUP_DB.AUX.DIM_MEMBER_GROUP                 TO ROLE ROLE_AIRFLOW;
GRANT SELECT ON MEETUP_DB.ANALYTICS.PROC_MEMBER_METRICS        TO ROLE ROLE_AIRFLOW;
GRANT SELECT ON MEETUP_DB.ANALYTICS.PROC_MEMBER_RECONCILIATION TO ROLE ROLE_AIRFLOW;
GRANT SELECT ON MEETUP_DB.OPS.MEMBER_METRICS_STATE             TO ROLE ROLE_AIRFLOW;

DESC TABLE MEETUP_DB.RAW.GROUPS;
DESC TABLE MEETUP_DB.RAW.MEMBERS_TOPICS;
DESC TABLE MEETUP_DB.RAW.TOPICS;

SELECT FILE_NAME, STATUS, ROWS_LOADED FROM MEETUP_DB.OPS.INGEST_CONTROL ORDER BY FILE_NAME;

SELECT COUNT(*) AS FILAS_RAW_MEMBERS FROM MEETUP_DB.RAW.MEMBERS;

SELECT TABLE_SCHEMA, TABLE_NAME, ROW_COUNT
FROM MEETUP_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME IN ('DIM_MEMBER_GROUP', 'PROC_MEMBER_METRICS',
                     'PROC_MEMBER_RECONCILIATION', 'MEMBER_METRICS_STATE')
ORDER BY TABLE_SCHEMA, TABLE_NAME;
